### ISSUE TITLE
Versioned Examples

### ISSUE THREAD

**Issue by Iamjava** [pfzetto/axum-oidc#8]
Hi, it would be nice if the (basic) examples are versioned, so that if I want to have a reference, I can just go and fetch the right version and don't have to dig through the history. If you think that is a good Idea, I would be willing to add a PR.

Many thanks for your work and Greetings from Germany  
Jan

**Comment by pfzetto** [comment]
Hello,
the examples folder only exists since the last version.
In future you should just be to checkout a specific tag (e.g. [0.2.3](https://github.com/pfzetto/axum-oidc/tree/0.2.3)).
Maybe I can write a github action that automatically creates an index for the `README.md`, so that there is every version with a link to the specific tag is listed.
I think that a manual versioning of the examples could be redundant if git already does that part (but I'm open to contrary arguments).

Paul

**Comment by Iamjava** [comment]
sounds wonderful, thank you

**Comment by pfzetto** [comment]
Hello,
I've just finished backporting the `basic` example to `v0.1`and `v0.2` and updated the README.
As the API doesn't change between patches I've created a branch for each minor version and pushed the example there.

Paul
